version: "3.8"
services:
  flask-app:
    ports:
      - 5000:5000
    build: flask-app
    environment: 
      ENV: development
      FLASK_APP: /code/server.py
      FLASK_ENV: development
    volumes:
      - ./flask-app:/code