version: "3.8"
services:
  flask-app:
    ports:
      - 5000:5000
    build: flask-app
    environment:
      ENV: production
      FLASK_APP: /code/server.py
      FLASK_ENV: production 
    restart: unless-stopped